version: "3.9"

services:
  database:
    image: mariadb:latest
    container_name: wp-database
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_LOCAL_HOME}:/var/lib/mysql
    command:
      - "--default_authentication_plugin=mysql_native_password"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - wordpress

  wordpress:
    image: wordpress:latest
    container_name: wp-wordpress
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - "80:80"
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html/wp-content
      - ${WORDPRESS_UPLOADS_CONFIG}:/usr/local/etc/php/conf.d/uploads.ini
      # - /path/to/repo/myTheme/:/var/www/html/wp-content/themes/myTheme
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    networks:
      - wordpress

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: wp-phpmyadmin
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - wordpress

  # adminer - bring up only as needed - bypasses nginx
#  adminer:
#    # default port 8080
#    image: adminer:4
#    container_name: wp-adminer
#    restart: unless-stopped
#    networks:
#      - wordpress
#    depends_on:
#      - database
#    ports:
#      - "9000:8080"

networks:
  wordpress:
    name: wp-wordpress
    driver: bridge
